<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\City;
class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
            ['country_code'=>'IN','city'=>'Mumbai','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'DL','state_code'=>'DL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bangalore','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Hyderabad','state_code'=>'TG','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ahmedabad','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Chennai','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kolkata','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Surat','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Pune','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jaipur','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Lucknow','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kanpur','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Nagpur','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Indore','state_code'=>'MP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Thane','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bhopal','state_code'=>'MP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Visakhapatnam','state_code'=>'AP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Pimpri & Chinchwad','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Patna','state_code'=>'BR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Vadodara','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ghaziabad','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ludhiana','state_code'=>'PB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Agra','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Nashik','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Faridabad','state_code'=>'HR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Meerut','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Rajkot','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kalyan & Dombivali','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Vasai Virar','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Varanasi','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Srinagar','state_code'=>'JK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Aurangabad','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Dhanbad','state_code'=>'JH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Amritsar','state_code'=>'PB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Navi Mumbai','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Allahabad','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ranchi','state_code'=>'JH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Haora','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Coimbatore','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jabalpur','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Gwalior','state_code'=>'MP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Vijayawada','state_code'=>'AP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jodhpur','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Madurai','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Raipur','state_code'=>'CT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kota','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Guwahati','state_code'=>'AS','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Chandigarh','state_code'=>'PB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Solapur','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Hubli and Dharwad','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bareilly','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Moradabad','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Gurgaon','state_code'=>'HR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Aligarh','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jalandhar','state_code'=>'PB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Tiruchirappalli','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bhubaneswar','state_code'=>'OR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Salem','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Mira and Bhayander','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Thiruvananthapuram','state_code'=>'KL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bhiwandi','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Saharanpur','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Gorakhpur','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Guntur','state_code'=>'AP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bikaner','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Amravati','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Noida','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jamshedpur','state_code'=>'JH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bhilai Nagar','state_code'=>'CT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Warangal','state_code'=>'TG','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Cuttack','state_code'=>'OR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Firozabad','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kochi','state_code'=>'KL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Bhavnagar','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Dehradun','state_code'=>'UT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Durgapur','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Asansol','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Nanded Waghala','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Kolapur','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ajmer','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Gulbarga','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jamnagar','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ujjain','state_code'=>'MP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Loni','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Siliguri','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jhansi','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ulhasnagar','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Nellore','state_code'=>'AP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jammu','state_code'=>'JK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Sangli Miraj Kupwad','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Belgaum','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Mangalore','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Ambattur','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Tirunelveli','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Malegoan','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Gaya','state_code'=>'BR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Jalgaon','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Udaipur','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'IN','city'=>'Maheshtala','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['country_code'=>'US','city'=>'Alexander City','state_code'=>'AL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],

        ];
        City::insert($countries);
    }
}
