<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Country;
class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
            [
                'country_code'=>'AF',
                'name'=>'Afghanistan',
                'phone_code'=>93,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'country_code'=>'AL',
                'name'=>'Albania',
                'phone_code'=>355,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
              'country_code'=>'DZ',
              'name'=>'Algeria',
              'phone_code'=>213,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AS',
              'name'=>'American Samoa',
              'phone_code'=>1684,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AD',
              'name'=>'Andorra',
              'phone_code'=>376,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AO',
              'name'=>'Angola',
              'phone_code'=>244,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AI',
              'name'=>'Anguilla',
              'phone_code'=>1264,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AQ',
              'name'=>'Antarctica',
              'phone_code'=>0,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AG',
              'name'=>'Antigua And Barbuda',
              'phone_code'=>1268,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AR',
              'name'=>'Argentina',
              'phone_code'=>54,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AM',
              'name'=>'Armenia',
              'phone_code'=>374,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AW',
              'name'=>'Aruba',
              'phone_code'=>297,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AU',
              'name'=>'Australia',
              'phone_code'=>61,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AT',
              'name'=>'Austria',
              'phone_code'=>43,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AZ',
              'name'=>'Azerbaijan',
              'phone_code'=>994,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BS',
              'name'=>'Bahamas The',
              'phone_code'=>1242,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BH',
              'name'=>'Bahrain',
              'phone_code'=>973,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BD',
              'name'=>'Bangladesh',
              'phone_code'=>880,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BB',
              'name'=>'Barbados',
              'phone_code'=>1246,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BY',
              'name'=>'Belarus',
              'phone_code'=>375,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BE',
              'name'=>'Belgium',
              'phone_code'=>32,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BZ',
              'name'=>'Belize',
              'phone_code'=>501,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BJ',
              'name'=>'Benin',
              'phone_code'=>229,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BM',
              'name'=>'Bermuda',
              'phone_code'=>1441,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BT',
              'name'=>'Bhutan',
              'phone_code'=>975,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BO',
              'name'=>'Bolivia',
              'phone_code'=>591,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BA',
              'name'=>'Bosnia and Herzegovina',
              'phone_code'=>387,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BW',
              'name'=>'Botswana',
              'phone_code'=>267,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BV',
              'name'=>'Bouvet Island',
              'phone_code'=>0,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BR',
              'name'=>'Brazil',
              'phone_code'=>55,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'IO',
              'name'=>'British Indian Ocean Territory',
              'phone_code'=>246,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BN',
              'name'=>'Brunei',
              'phone_code'=>673,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BG',
              'name'=>'Bulgaria',
              'phone_code'=>359,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BF',
              'name'=>'Burkina Faso',
              'phone_code'=>226,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BI',
              'name'=>'Burundi',
              'phone_code'=>257,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'KH',
              'name'=>'Cambodia',
              'phone_code'=>855,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CM',
              'name'=>'Cameroon',
              'phone_code'=>237,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CA',
              'name'=>'Canada',
              'phone_code'=>1,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CV',
              'name'=>'Cape Verde',
              'phone_code'=>238,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'KY',
              'name'=>'Cayman Islands',
              'phone_code'=>1345,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],[
       'country_code'=>'CF',
       'name'=>'Central African Republic',
       'phone_code'=>236,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TD',
       'name'=>'Chad',
       'phone_code'=>235,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CL',
       'name'=>'Chile',
       'phone_code'=>56,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CN',
       'name'=>'China',
       'phone_code'=>86,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CX',
       'name'=>'Christmas Island',
       'phone_code'=>61,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CC',
       'name'=>'Cocos (Keeling) Islands',
       'phone_code'=>672,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CO',
       'name'=>'Colombia',
       'phone_code'=>57,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KM',
       'name'=>'Comoros',
       'phone_code'=>269,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CG',
       'name'=>'Republic Of The Congo',
       'phone_code'=>242,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CD',
       'name'=>'Democratic Republic Of The Congo',
       'phone_code'=>242,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CK',
       'name'=>'Cook Islands',
       'phone_code'=>682,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CR',
       'name'=>'Costa Rica',
       'phone_code'=>506,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CI',
       'name'=>'Cote D Ivoire (Ivory Coast)',
       'phone_code'=>225,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HR',
       'name'=>'Croatia (Hrvatska)',
       'phone_code'=>385,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CU',
       'name'=>'Cuba',
       'phone_code'=>53,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CY',
       'name'=>'Cyprus',
       'phone_code'=>357,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CZ',
       'name'=>'Czech Republic',
       'phone_code'=>420,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DK',
       'name'=>'Denmark',
       'phone_code'=>45,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DJ',
       'name'=>'Djibouti',
       'phone_code'=>253,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DM',
       'name'=>'Dominica',
       'phone_code'=>1767,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DO',
       'name'=>'Dominican Republic',
       'phone_code'=>1809,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TP',
       'name'=>'East Timor',
       'phone_code'=>670,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EC',
       'name'=>'Ecuador',
       'phone_code'=>593,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EG',
       'name'=>'Egypt',
       'phone_code'=>20,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SV',
       'name'=>'El Salvador',
       'phone_code'=>503,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GQ',
       'name'=>'Equatorial Guinea',
       'phone_code'=>240,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ER',
       'name'=>'Eritrea',
       'phone_code'=>291,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EE',
       'name'=>'Estonia',
       'phone_code'=>372,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ET',
       'name'=>'Ethiopia',
       'phone_code'=>251,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XA',
       'name'=>'External Territories of Australia',
       'phone_code'=>61,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FK',
       'name'=>'Falkland Islands',
       'phone_code'=>500,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FO',
       'name'=>'Faroe Islands',
       'phone_code'=>298,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FJ',
       'name'=>'Fiji Islands',
       'phone_code'=>679,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FI',
       'name'=>'Finland',
       'phone_code'=>358,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FR',
       'name'=>'France',
       'phone_code'=>33,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GF',
       'name'=>'French Guiana',
       'phone_code'=>594,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PF',
       'name'=>'French Polynesia',
       'phone_code'=>689,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TF',
       'name'=>'French Southern Territories',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GA',
       'name'=>'Gabon',
       'phone_code'=>241,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GM',
       'name'=>'Gambia The',
       'phone_code'=>220,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GE',
       'name'=>'Georgia',
       'phone_code'=>995,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DE',
       'name'=>'Germany',
       'phone_code'=>49,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GH',
       'name'=>'Ghana',
       'phone_code'=>233,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GI',
       'name'=>'Gibraltar',
       'phone_code'=>350,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GR',
       'name'=>'Greece',
       'phone_code'=>30,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GL',
       'name'=>'Greenland',
       'phone_code'=>299,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GD',
       'name'=>'Grenada',
       'phone_code'=>1473,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GP',
       'name'=>'Guadeloupe',
       'phone_code'=>590,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GU',
       'name'=>'Guam',
       'phone_code'=>1671,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GT',
       'name'=>'Guatemala',
       'phone_code'=>502,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XU',
       'name'=>'Guernsey and Alderney',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GN',
       'name'=>'Guinea',
       'phone_code'=>224,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GW',
       'name'=>'Guinea-Bissau',
       'phone_code'=>245,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GY',
       'name'=>'Guyana',
       'phone_code'=>592,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HT',
       'name'=>'Haiti',
       'phone_code'=>509,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HM',
       'name'=>'Heard and McDonald Islands',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HN',
       'name'=>'Honduras',
       'phone_code'=>504,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HK',
       'name'=>'Hong Kong S.A.R.',
       'phone_code'=>852,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HU',
       'name'=>'Hungary',
       'phone_code'=>36,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IS',
       'name'=>'Iceland',
       'phone_code'=>354,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IN',
       'name'=>'India',
       'phone_code'=>91,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'id',
       'name'=>'Indonesia',
       'phone_code'=>62,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IR',
       'name'=>'Iran',
       'phone_code'=>98,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IQ',
       'name'=>'Iraq',
       'phone_code'=>964,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IE',
       'name'=>'Ireland',
       'phone_code'=>353,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IL',
       'name'=>'Israel',
       'phone_code'=>972,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IT',
       'name'=>'Italy',
       'phone_code'=>39,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JM',
       'name'=>'Jamaica',
       'phone_code'=>1876,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JP',
       'name'=>'Japan',
       'phone_code'=>81,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XJ',
       'name'=>'Jersey',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JO',
       'name'=>'Jordan',
       'phone_code'=>962,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KZ',
       'name'=>'Kazakhstan',
       'phone_code'=>7,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KE',
       'name'=>'Kenya',
       'phone_code'=>254,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KI',
       'name'=>'Kiribati',
       'phone_code'=>686,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KP',
       'name'=>'Korea North',
       'phone_code'=>850,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KR',
       'name'=>'Korea South',
       'phone_code'=>82,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KW',
       'name'=>'Kuwait',
       'phone_code'=>965,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KG',
       'name'=>'Kyrgyzstan',
       'phone_code'=>996,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LA',
       'name'=>'Laos',
       'phone_code'=>856,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LV',
       'name'=>'Latvia',
       'phone_code'=>371,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LB',
       'name'=>'Lebanon',
       'phone_code'=>961,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LS',
       'name'=>'Lesotho',
       'phone_code'=>266,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LR',
       'name'=>'Liberia',
       'phone_code'=>231,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LY',
       'name'=>'Libya',
       'phone_code'=>218,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LI',
       'name'=>'Liechtenstein',
       'phone_code'=>423,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LT',
       'name'=>'Lithuania',
       'phone_code'=>370,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LU',
       'name'=>'Luxembourg',
       'phone_code'=>352,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MO',
       'name'=>'Macau S.A.R.',
       'phone_code'=>853,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MK',
       'name'=>'Macedonia',
       'phone_code'=>389,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MG',
       'name'=>'Madagascar',
       'phone_code'=>261,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MW',
       'name'=>'Malawi',
       'phone_code'=>265,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MY',
       'name'=>'Malaysia',
       'phone_code'=>60,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MV',
       'name'=>'Maldives',
       'phone_code'=>960,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ML',
       'name'=>'Mali',
       'phone_code'=>223,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MT',
       'name'=>'Malta',
       'phone_code'=>356,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XM',
       'name'=>'Man (Isle of)',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MH',
       'name'=>'Marshall Islands',
       'phone_code'=>692,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MQ',
       'name'=>'Martinique',
       'phone_code'=>596,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MR',
       'name'=>'Mauritania',
       'phone_code'=>222,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MU',
       'name'=>'Mauritius',
       'phone_code'=>230,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YT',
       'name'=>'Mayotte',
       'phone_code'=>269,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MX',
       'name'=>'Mexico',
       'phone_code'=>52,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FM',
       'name'=>'Micronesia',
       'phone_code'=>691,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MD',
       'name'=>'Moldova',
       'phone_code'=>373,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MC',
       'name'=>'Monaco',
       'phone_code'=>377,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MN',
       'name'=>'Mongolia',
       'phone_code'=>976,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MS',
       'name'=>'Montserrat',
       'phone_code'=>1664,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MA',
       'name'=>'Morocco',
       'phone_code'=>212,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MZ',
       'name'=>'Mozambique',
       'phone_code'=>258,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MM',
       'name'=>'Myanmar',
       'phone_code'=>95,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NA',
       'name'=>'Namibia',
       'phone_code'=>264,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NR',
       'name'=>'Nauru',
       'phone_code'=>674,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NP',
       'name'=>'Nepal',
       'phone_code'=>977,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'AN',
       'name'=>'Netherlands Antilles',
       'phone_code'=>599,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NL',
       'name'=>'Netherlands The',
       'phone_code'=>31,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NC',
       'name'=>'New Caledonia',
       'phone_code'=>687,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NZ',
       'name'=>'New Zealand',
       'phone_code'=>64,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NI',
       'name'=>'Nicaragua',
       'phone_code'=>505,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NE',
       'name'=>'Niger',
       'phone_code'=>227,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NG',
       'name'=>'Nigeria',
       'phone_code'=>234,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NU',
       'name'=>'Niue',
       'phone_code'=>683,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NF',
       'name'=>'Norfolk Island',
       'phone_code'=>672,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MP',
       'name'=>'Northern Mariana Islands',
       'phone_code'=>1670,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NO',
       'name'=>'Norway',
       'phone_code'=>47,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'OM',
       'name'=>'Oman',
       'phone_code'=>968,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PK',
       'name'=>'Pakistan',
       'phone_code'=>92,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PW',
       'name'=>'Palau',
       'phone_code'=>680,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PS',
       'name'=>'Palestinian Territory Occupied',
       'phone_code'=>970,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PA',
       'name'=>'Panama',
       'phone_code'=>507,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PG',
       'name'=>'Papua new Guinea',
       'phone_code'=>675,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PY',
       'name'=>'Paraguay',
       'phone_code'=>595,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PE',
       'name'=>'Peru',
       'phone_code'=>51,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PH',
       'name'=>'Philippines',
       'phone_code'=>63,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PN',
       'name'=>'Pitcairn Island',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PL',
       'name'=>'Poland',
       'phone_code'=>48,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PT',
       'name'=>'Portugal',
       'phone_code'=>351,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PR',
       'name'=>'Puerto Rico',
       'phone_code'=>1787,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'QA',
       'name'=>'Qatar',
       'phone_code'=>974,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RE',
       'name'=>'Reunion',
       'phone_code'=>262,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RO',
       'name'=>'Romania',
       'phone_code'=>40,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RU',
       'name'=>'Russia',
       'phone_code'=>70,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RW',
       'name'=>'Rwanda',
       'phone_code'=>250,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SH',
       'name'=>'Saint Helena',
       'phone_code'=>290,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KN',
       'name'=>'Saint Kitts And Nevis',
       'phone_code'=>1869,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LC',
       'name'=>'Saint Lucia',
       'phone_code'=>1758,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PM',
       'name'=>'Saint Pierre and Miquelon',
       'phone_code'=>508,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VC',
       'name'=>'Saint Vincent And The Grenadines',
       'phone_code'=>1784,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'WS',
       'name'=>'Samoa',
       'phone_code'=>684,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SM',
       'name'=>'San Marino',
       'phone_code'=>378,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ST',
       'name'=>'Sao Tome and Principe',
       'phone_code'=>239,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SA',
       'name'=>'Saudi Arabia',
       'phone_code'=>966,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SN',
       'name'=>'Senegal',
       'phone_code'=>221,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RS',
       'name'=>'Serbia',
       'phone_code'=>381,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SC',
       'name'=>'Seychelles',
       'phone_code'=>248,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SL',
       'name'=>'Sierra Leone',
       'phone_code'=>232,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SG',
       'name'=>'Singapore',
       'phone_code'=>65,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SK',
       'name'=>'Slovakia',
       'phone_code'=>421,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SI',
       'name'=>'Slovenia',
       'phone_code'=>386,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XG',
       'name'=>'Smaller Territories of the UK',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SB',
       'name'=>'Solomon Islands',
       'phone_code'=>677,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SO',
       'name'=>'Somalia',
       'phone_code'=>252,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZA',
       'name'=>'South Africa',
       'phone_code'=>27,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GS',
       'name'=>'South Georgia',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SS',
       'name'=>'South Sudan',
       'phone_code'=>211,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ES',
       'name'=>'Spain',
       'phone_code'=>34,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LK',
       'name'=>'Sri Lanka',
       'phone_code'=>94,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SD',
       'name'=>'Sudan',
       'phone_code'=>249,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SR',
       'name'=>'Suricountry',
       'phone_code'=>597,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SJ',
       'name'=>'Svalbard And Jan Mayen Islands',
       'phone_code'=>47,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SZ',
       'name'=>'Swaziland',
       'phone_code'=>268,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SE',
       'name'=>'Sweden',
       'phone_code'=>46,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CH',
       'name'=>'Switzerland',
       'phone_code'=>41,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SY',
       'name'=>'Syria',
       'phone_code'=>963,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TW',
       'name'=>'Taiwan',
       'phone_code'=>886,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TJ',
       'name'=>'Tajikistan',
       'phone_code'=>992,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TZ',
       'name'=>'Tanzania',
       'phone_code'=>255,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TH',
       'name'=>'Thailand',
       'phone_code'=>66,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TG',
       'name'=>'Togo',
       'phone_code'=>228,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TK',
       'name'=>'Tokelau',
       'phone_code'=>690,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TO',
       'name'=>'Tonga',
       'phone_code'=>676,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TT',
       'name'=>'Trinidad And Tobago',
       'phone_code'=>1868,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TN',
       'name'=>'Tunisia',
       'phone_code'=>216,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TR',
       'name'=>'Turkey',
       'phone_code'=>90,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TM',
       'name'=>'Turkmenistan',
       'phone_code'=>7370,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TC',
       'name'=>'Turks And Caicos Islands',
       'phone_code'=>1649,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TV',
       'name'=>'Tuvalu',
       'phone_code'=>688,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UG',
       'name'=>'Uganda',
       'phone_code'=>256,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UA',
       'name'=>'Ukraine',
       'phone_code'=>380,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'AE',
       'name'=>'United Arab Emirates',
       'phone_code'=>971,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GB',
       'name'=>'United Kingdom',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'US',
       'name'=>'United States',
       'phone_code'=>1,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UM',
       'name'=>'United States Minor Outlying Islands',
       'phone_code'=>1,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UY',
       'name'=>'Uruguay',
       'phone_code'=>598,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UZ',
       'name'=>'Uzbekistan',
       'phone_code'=>998,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VU',
       'name'=>'Vanuatu',
       'phone_code'=>678,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VA',
       'name'=>'Vatican City State (Holy See)',
       'phone_code'=>39,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VE',
       'name'=>'Venezuela',
       'phone_code'=>58,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VN',
       'name'=>'Vietnam',
       'phone_code'=>84,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VG',
       'name'=>'Virgin Islands (British)',
       'phone_code'=>1284,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VI',
       'name'=>'Virgin Islands (US)',
       'phone_code'=>1340,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'WF',
       'name'=>'Wallis And Futuna Islands',
       'phone_code'=>681,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EH',
       'name'=>'Western Sahara',
       'phone_code'=>212,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YE',
       'name'=>'Yemen',
       'phone_code'=>967,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YU',
       'name'=>'Yugoslavia',
       'phone_code'=>38,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZM',
       'name'=>'Zambia',
       'phone_code'=>260,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZW',
       'name'=>'Zimbabwe',
       'phone_code'=>26,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],];
           Country::insert($countries);
    }
}
