<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Country;
class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
            [
                'country_code'=>'AF',
                'country'=>'Afghanistan',
                'phone_code'=>93,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'country_code'=>'AL',
                'country'=>'Albania',
                'phone_code'=>355,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
              'country_code'=>'DZ',
              'country'=>'Algeria',
              'phone_code'=>213,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AS',
              'country'=>'American Samoa',
              'phone_code'=>1684,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AD',
              'country'=>'Andorra',
              'phone_code'=>376,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AO',
              'country'=>'Angola',
              'phone_code'=>244,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AI',
              'country'=>'Anguilla',
              'phone_code'=>1264,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AQ',
              'country'=>'Antarctica',
              'phone_code'=>0,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AG',
              'country'=>'Antigua And Barbuda',
              'phone_code'=>1268,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AR',
              'country'=>'Argentina',
              'phone_code'=>54,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AM',
              'country'=>'Armenia',
              'phone_code'=>374,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AW',
              'country'=>'Aruba',
              'phone_code'=>297,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AU',
              'country'=>'Australia',
              'phone_code'=>61,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AT',
              'country'=>'Austria',
              'phone_code'=>43,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'AZ',
              'country'=>'Azerbaijan',
              'phone_code'=>994,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BS',
              'country'=>'Bahamas The',
              'phone_code'=>1242,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BH',
              'country'=>'Bahrain',
              'phone_code'=>973,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BD',
              'country'=>'Bangladesh',
              'phone_code'=>880,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BB',
              'country'=>'Barbados',
              'phone_code'=>1246,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BY',
              'country'=>'Belarus',
              'phone_code'=>375,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BE',
              'country'=>'Belgium',
              'phone_code'=>32,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BZ',
              'country'=>'Belize',
              'phone_code'=>501,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BJ',
              'country'=>'Benin',
              'phone_code'=>229,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BM',
              'country'=>'Bermuda',
              'phone_code'=>1441,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BT',
              'country'=>'Bhutan',
              'phone_code'=>975,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BO',
              'country'=>'Bolivia',
              'phone_code'=>591,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BA',
              'country'=>'Bosnia and Herzegovina',
              'phone_code'=>387,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BW',
              'country'=>'Botswana',
              'phone_code'=>267,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BV',
              'country'=>'Bouvet Island',
              'phone_code'=>0,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BR',
              'country'=>'Brazil',
              'phone_code'=>55,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'IO',
              'country'=>'British Indian Ocean Territory',
              'phone_code'=>246,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BN',
              'country'=>'Brunei',
              'phone_code'=>673,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BG',
              'country'=>'Bulgaria',
              'phone_code'=>359,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BF',
              'country'=>'Burkina Faso',
              'phone_code'=>226,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'BI',
              'country'=>'Burundi',
              'phone_code'=>257,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'KH',
              'country'=>'Cambodia',
              'phone_code'=>855,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CM',
              'country'=>'Cameroon',
              'phone_code'=>237,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CA',
              'country'=>'Canada',
              'phone_code'=>1,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'CV',
              'country'=>'Cape Verde',
              'phone_code'=>238,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],
        [
              'country_code'=>'KY',
              'country'=>'Cayman Islands',
              'phone_code'=>1345,
'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
 ],[
       'country_code'=>'CF',
       'country'=>'Central African Republic',
       'phone_code'=>236,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TD',
       'country'=>'Chad',
       'phone_code'=>235,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CL',
       'country'=>'Chile',
       'phone_code'=>56,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CN',
       'country'=>'China',
       'phone_code'=>86,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CX',
       'country'=>'Christmas Island',
       'phone_code'=>61,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CC',
       'country'=>'Cocos (Keeling) Islands',
       'phone_code'=>672,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CO',
       'country'=>'Colombia',
       'phone_code'=>57,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KM',
       'country'=>'Comoros',
       'phone_code'=>269,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CG',
       'country'=>'Republic Of The Congo',
       'phone_code'=>242,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CD',
       'country'=>'Democratic Republic Of The Congo',
       'phone_code'=>242,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CK',
       'country'=>'Cook Islands',
       'phone_code'=>682,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CR',
       'country'=>'Costa Rica',
       'phone_code'=>506,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CI',
       'country'=>'Cote D Ivoire (Ivory Coast)',
       'phone_code'=>225,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HR',
       'country'=>'Croatia (Hrvatska)',
       'phone_code'=>385,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CU',
       'country'=>'Cuba',
       'phone_code'=>53,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CY',
       'country'=>'Cyprus',
       'phone_code'=>357,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CZ',
       'country'=>'Czech Republic',
       'phone_code'=>420,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DK',
       'country'=>'Denmark',
       'phone_code'=>45,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DJ',
       'country'=>'Djibouti',
       'phone_code'=>253,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DM',
       'country'=>'Dominica',
       'phone_code'=>1767,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DO',
       'country'=>'Dominican Republic',
       'phone_code'=>1809,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TP',
       'country'=>'East Timor',
       'phone_code'=>670,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EC',
       'country'=>'Ecuador',
       'phone_code'=>593,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EG',
       'country'=>'Egypt',
       'phone_code'=>20,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SV',
       'country'=>'El Salvador',
       'phone_code'=>503,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GQ',
       'country'=>'Equatorial Guinea',
       'phone_code'=>240,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ER',
       'country'=>'Eritrea',
       'phone_code'=>291,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EE',
       'country'=>'Estonia',
       'phone_code'=>372,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ET',
       'country'=>'Ethiopia',
       'phone_code'=>251,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XA',
       'country'=>'External Territories of Australia',
       'phone_code'=>61,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FK',
       'country'=>'Falkland Islands',
       'phone_code'=>500,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FO',
       'country'=>'Faroe Islands',
       'phone_code'=>298,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FJ',
       'country'=>'Fiji Islands',
       'phone_code'=>679,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FI',
       'country'=>'Finland',
       'phone_code'=>358,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FR',
       'country'=>'France',
       'phone_code'=>33,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GF',
       'country'=>'French Guiana',
       'phone_code'=>594,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PF',
       'country'=>'French Polynesia',
       'phone_code'=>689,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TF',
       'country'=>'French Southern Territories',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GA',
       'country'=>'Gabon',
       'phone_code'=>241,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GM',
       'country'=>'Gambia The',
       'phone_code'=>220,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GE',
       'country'=>'Georgia',
       'phone_code'=>995,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'DE',
       'country'=>'Germany',
       'phone_code'=>49,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GH',
       'country'=>'Ghana',
       'phone_code'=>233,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GI',
       'country'=>'Gibraltar',
       'phone_code'=>350,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GR',
       'country'=>'Greece',
       'phone_code'=>30,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GL',
       'country'=>'Greenland',
       'phone_code'=>299,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GD',
       'country'=>'Grenada',
       'phone_code'=>1473,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GP',
       'country'=>'Guadeloupe',
       'phone_code'=>590,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GU',
       'country'=>'Guam',
       'phone_code'=>1671,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GT',
       'country'=>'Guatemala',
       'phone_code'=>502,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XU',
       'country'=>'Guernsey and Alderney',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GN',
       'country'=>'Guinea',
       'phone_code'=>224,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GW',
       'country'=>'Guinea-Bissau',
       'phone_code'=>245,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GY',
       'country'=>'Guyana',
       'phone_code'=>592,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HT',
       'country'=>'Haiti',
       'phone_code'=>509,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HM',
       'country'=>'Heard and McDonald Islands',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HN',
       'country'=>'Honduras',
       'phone_code'=>504,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HK',
       'country'=>'Hong Kong S.A.R.',
       'phone_code'=>852,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'HU',
       'country'=>'Hungary',
       'phone_code'=>36,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IS',
       'country'=>'Iceland',
       'phone_code'=>354,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IN',
       'country'=>'India',
       'phone_code'=>91,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'id',
       'country'=>'Indonesia',
       'phone_code'=>62,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IR',
       'country'=>'Iran',
       'phone_code'=>98,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IQ',
       'country'=>'Iraq',
       'phone_code'=>964,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IE',
       'country'=>'Ireland',
       'phone_code'=>353,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IL',
       'country'=>'Israel',
       'phone_code'=>972,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'IT',
       'country'=>'Italy',
       'phone_code'=>39,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JM',
       'country'=>'Jamaica',
       'phone_code'=>1876,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JP',
       'country'=>'Japan',
       'phone_code'=>81,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XJ',
       'country'=>'Jersey',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'JO',
       'country'=>'Jordan',
       'phone_code'=>962,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KZ',
       'country'=>'Kazakhstan',
       'phone_code'=>7,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KE',
       'country'=>'Kenya',
       'phone_code'=>254,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KI',
       'country'=>'Kiribati',
       'phone_code'=>686,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KP',
       'country'=>'Korea North',
       'phone_code'=>850,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KR',
       'country'=>'Korea South',
       'phone_code'=>82,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KW',
       'country'=>'Kuwait',
       'phone_code'=>965,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KG',
       'country'=>'Kyrgyzstan',
       'phone_code'=>996,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LA',
       'country'=>'Laos',
       'phone_code'=>856,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LV',
       'country'=>'Latvia',
       'phone_code'=>371,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LB',
       'country'=>'Lebanon',
       'phone_code'=>961,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LS',
       'country'=>'Lesotho',
       'phone_code'=>266,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LR',
       'country'=>'Liberia',
       'phone_code'=>231,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LY',
       'country'=>'Libya',
       'phone_code'=>218,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LI',
       'country'=>'Liechtenstein',
       'phone_code'=>423,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LT',
       'country'=>'Lithuania',
       'phone_code'=>370,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LU',
       'country'=>'Luxembourg',
       'phone_code'=>352,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MO',
       'country'=>'Macau S.A.R.',
       'phone_code'=>853,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MK',
       'country'=>'Macedonia',
       'phone_code'=>389,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MG',
       'country'=>'Madagascar',
       'phone_code'=>261,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MW',
       'country'=>'Malawi',
       'phone_code'=>265,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MY',
       'country'=>'Malaysia',
       'phone_code'=>60,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MV',
       'country'=>'Maldives',
       'phone_code'=>960,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ML',
       'country'=>'Mali',
       'phone_code'=>223,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MT',
       'country'=>'Malta',
       'phone_code'=>356,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XM',
       'country'=>'Man (Isle of)',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MH',
       'country'=>'Marshall Islands',
       'phone_code'=>692,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MQ',
       'country'=>'Martinique',
       'phone_code'=>596,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MR',
       'country'=>'Mauritania',
       'phone_code'=>222,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MU',
       'country'=>'Mauritius',
       'phone_code'=>230,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YT',
       'country'=>'Mayotte',
       'phone_code'=>269,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MX',
       'country'=>'Mexico',
       'phone_code'=>52,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'FM',
       'country'=>'Micronesia',
       'phone_code'=>691,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MD',
       'country'=>'Moldova',
       'phone_code'=>373,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MC',
       'country'=>'Monaco',
       'phone_code'=>377,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MN',
       'country'=>'Mongolia',
       'phone_code'=>976,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MS',
       'country'=>'Montserrat',
       'phone_code'=>1664,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MA',
       'country'=>'Morocco',
       'phone_code'=>212,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MZ',
       'country'=>'Mozambique',
       'phone_code'=>258,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MM',
       'country'=>'Myanmar',
       'phone_code'=>95,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NA',
       'country'=>'Namibia',
       'phone_code'=>264,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NR',
       'country'=>'Nauru',
       'phone_code'=>674,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NP',
       'country'=>'Nepal',
       'phone_code'=>977,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'AN',
       'country'=>'Netherlands Antilles',
       'phone_code'=>599,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NL',
       'country'=>'Netherlands The',
       'phone_code'=>31,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NC',
       'country'=>'New Caledonia',
       'phone_code'=>687,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NZ',
       'country'=>'New Zealand',
       'phone_code'=>64,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NI',
       'country'=>'Nicaragua',
       'phone_code'=>505,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NE',
       'country'=>'Niger',
       'phone_code'=>227,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NG',
       'country'=>'Nigeria',
       'phone_code'=>234,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NU',
       'country'=>'Niue',
       'phone_code'=>683,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NF',
       'country'=>'Norfolk Island',
       'phone_code'=>672,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'MP',
       'country'=>'Northern Mariana Islands',
       'phone_code'=>1670,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'NO',
       'country'=>'Norway',
       'phone_code'=>47,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'OM',
       'country'=>'Oman',
       'phone_code'=>968,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PK',
       'country'=>'Pakistan',
       'phone_code'=>92,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PW',
       'country'=>'Palau',
       'phone_code'=>680,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PS',
       'country'=>'Palestinian Territory Occupied',
       'phone_code'=>970,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PA',
       'country'=>'Panama',
       'phone_code'=>507,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PG',
       'country'=>'Papua new Guinea',
       'phone_code'=>675,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PY',
       'country'=>'Paraguay',
       'phone_code'=>595,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PE',
       'country'=>'Peru',
       'phone_code'=>51,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PH',
       'country'=>'Philippines',
       'phone_code'=>63,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PN',
       'country'=>'Pitcairn Island',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PL',
       'country'=>'Poland',
       'phone_code'=>48,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PT',
       'country'=>'Portugal',
       'phone_code'=>351,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PR',
       'country'=>'Puerto Rico',
       'phone_code'=>1787,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'QA',
       'country'=>'Qatar',
       'phone_code'=>974,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RE',
       'country'=>'Reunion',
       'phone_code'=>262,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RO',
       'country'=>'Romania',
       'phone_code'=>40,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RU',
       'country'=>'Russia',
       'phone_code'=>70,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RW',
       'country'=>'Rwanda',
       'phone_code'=>250,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SH',
       'country'=>'Saint Helena',
       'phone_code'=>290,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'KN',
       'country'=>'Saint Kitts And Nevis',
       'phone_code'=>1869,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LC',
       'country'=>'Saint Lucia',
       'phone_code'=>1758,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'PM',
       'country'=>'Saint Pierre and Miquelon',
       'phone_code'=>508,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VC',
       'country'=>'Saint Vincent And The Grenadines',
       'phone_code'=>1784,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'WS',
       'country'=>'Samoa',
       'phone_code'=>684,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SM',
       'country'=>'San Marino',
       'phone_code'=>378,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ST',
       'country'=>'Sao Tome and Principe',
       'phone_code'=>239,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SA',
       'country'=>'Saudi Arabia',
       'phone_code'=>966,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SN',
       'country'=>'Senegal',
       'phone_code'=>221,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'RS',
       'country'=>'Serbia',
       'phone_code'=>381,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SC',
       'country'=>'Seychelles',
       'phone_code'=>248,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SL',
       'country'=>'Sierra Leone',
       'phone_code'=>232,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SG',
       'country'=>'Singapore',
       'phone_code'=>65,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SK',
       'country'=>'Slovakia',
       'phone_code'=>421,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SI',
       'country'=>'Slovenia',
       'phone_code'=>386,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'XG',
       'country'=>'Smaller Territories of the UK',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SB',
       'country'=>'Solomon Islands',
       'phone_code'=>677,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SO',
       'country'=>'Somalia',
       'phone_code'=>252,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZA',
       'country'=>'South Africa',
       'phone_code'=>27,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GS',
       'country'=>'South Georgia',
       'phone_code'=>0,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SS',
       'country'=>'South Sudan',
       'phone_code'=>211,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ES',
       'country'=>'Spain',
       'phone_code'=>34,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'LK',
       'country'=>'Sri Lanka',
       'phone_code'=>94,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SD',
       'country'=>'Sudan',
       'phone_code'=>249,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SR',
       'country'=>'Suricountry',
       'phone_code'=>597,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SJ',
       'country'=>'Svalbard And Jan Mayen Islands',
       'phone_code'=>47,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SZ',
       'country'=>'Swaziland',
       'phone_code'=>268,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SE',
       'country'=>'Sweden',
       'phone_code'=>46,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'CH',
       'country'=>'Switzerland',
       'phone_code'=>41,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'SY',
       'country'=>'Syria',
       'phone_code'=>963,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TW',
       'country'=>'Taiwan',
       'phone_code'=>886,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TJ',
       'country'=>'Tajikistan',
       'phone_code'=>992,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TZ',
       'country'=>'Tanzania',
       'phone_code'=>255,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TH',
       'country'=>'Thailand',
       'phone_code'=>66,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TG',
       'country'=>'Togo',
       'phone_code'=>228,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TK',
       'country'=>'Tokelau',
       'phone_code'=>690,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TO',
       'country'=>'Tonga',
       'phone_code'=>676,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TT',
       'country'=>'Trinidad And Tobago',
       'phone_code'=>1868,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TN',
       'country'=>'Tunisia',
       'phone_code'=>216,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TR',
       'country'=>'Turkey',
       'phone_code'=>90,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TM',
       'country'=>'Turkmenistan',
       'phone_code'=>7370,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TC',
       'country'=>'Turks And Caicos Islands',
       'phone_code'=>1649,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'TV',
       'country'=>'Tuvalu',
       'phone_code'=>688,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UG',
       'country'=>'Uganda',
       'phone_code'=>256,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UA',
       'country'=>'Ukraine',
       'phone_code'=>380,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'AE',
       'country'=>'United Arab Emirates',
       'phone_code'=>971,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'GB',
       'country'=>'United Kingdom',
       'phone_code'=>44,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'US',
       'country'=>'United States',
       'phone_code'=>1,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UM',
       'country'=>'United States Minor Outlying Islands',
       'phone_code'=>1,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UY',
       'country'=>'Uruguay',
       'phone_code'=>598,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'UZ',
       'country'=>'Uzbekistan',
       'phone_code'=>998,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VU',
       'country'=>'Vanuatu',
       'phone_code'=>678,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VA',
       'country'=>'Vatican City State (Holy See)',
       'phone_code'=>39,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VE',
       'country'=>'Venezuela',
       'phone_code'=>58,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VN',
       'country'=>'Vietnam',
       'phone_code'=>84,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VG',
       'country'=>'Virgin Islands (British)',
       'phone_code'=>1284,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'VI',
       'country'=>'Virgin Islands (US)',
       'phone_code'=>1340,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'WF',
       'country'=>'Wallis And Futuna Islands',
       'phone_code'=>681,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'EH',
       'country'=>'Western Sahara',
       'phone_code'=>212,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YE',
       'country'=>'Yemen',
       'phone_code'=>967,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'YU',
       'country'=>'Yugoslavia',
       'phone_code'=>38,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZM',
       'country'=>'Zambia',
       'phone_code'=>260,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],
     [
       'country_code'=>'ZW',
       'country'=>'Zimbabwe',
       'phone_code'=>26,
     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     ],];
           Country::insert($countries);
    }
}
