<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\State;
class StatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
          ['country_code'=>'IN','state'=>'Andaman and Nicobar Islands','state_code'=>'AN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Andhra Pradesh','state_code'=>'AP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Arunachal Pradesh','state_code'=>'AR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Assam','state_code'=>'AS','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Bihar','state_code'=>'BR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Chandigarh','state_code'=>'CH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Chhattisgarh','state_code'=>'CT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Dadra and Nagar Haveli','state_code'=>'DN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Daman and Diu','state_code'=>'DD','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Delhi','state_code'=>'DL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Goa','state_code'=>'GA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Gujarat','state_code'=>'GJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Haryana','state_code'=>'HR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Himachal Pradesh','state_code'=>'HP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Jammu and Kashmir','state_code'=>'JK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Jharkhand','state_code'=>'JH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Karnataka','state_code'=>'KA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Kerala','state_code'=>'KL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Lakshadweep','state_code'=>'LD','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Madhya Pradesh','state_code'=>'MP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Maharashtra','state_code'=>'MH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Manipur','state_code'=>'MN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Meghalaya','state_code'=>'ML','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Mizoram','state_code'=>'MZ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Nagaland','state_code'=>'NL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Odisha','state_code'=>'OR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Puducherry','state_code'=>'PY','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Punjab','state_code'=>'PB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Rajasthan','state_code'=>'RJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Sikkim','state_code'=>'SK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Tamil Nadu','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Telangana','state_code'=>'TG','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Tripura','state_code'=>'TR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Uttar Pradesh','state_code'=>'UP','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'Uttarakhand','state_code'=>'UT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'IN','state'=>'West Bengal','state_code'=>'WB','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Alabama','state_code'=>'AL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Alaska','state_code'=>'AK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Arizona','state_code'=>'AZ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Arkansas','state_code'=>'AR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'California','state_code'=>'CA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Colorado','state_code'=>'CO','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Connecticut','state_code'=>'CT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Delaware','state_code'=>'DE','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'District of Columbia','state_code'=>'DC','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Florida','state_code'=>'FL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Georgia','state_code'=>'GA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Hawaii','state_code'=>'HI','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Idaho','state_code'=>'ID','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Illinois','state_code'=>'IL','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Indiana','state_code'=>'IN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Iowa','state_code'=>'IA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Kansas','state_code'=>'KS','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Kentucky','state_code'=>'KY','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Louisiana','state_code'=>'LA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Maine','state_code'=>'ME','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Maryland','state_code'=>'MD','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Massachusetts','state_code'=>'MA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Michigan','state_code'=>'MI','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Minnesota','state_code'=>'MN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Mississippi','state_code'=>'MS','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Missouri','state_code'=>'MO','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Montana','state_code'=>'MT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Nebraska','state_code'=>'NE','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Nevada','state_code'=>'NV','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'New Hampshire','state_code'=>'NH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'New Jersey','state_code'=>'NJ','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'New Mexico','state_code'=>'NM','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'New York','state_code'=>'NY','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'North Carolina','state_code'=>'NC','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'North Dakota','state_code'=>'ND','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Ohio','state_code'=>'OH','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Oklahoma','state_code'=>'OK','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Oregon','state_code'=>'OR','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Pennsylvania','state_code'=>'PA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Rhode Island','state_code'=>'RI','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'South Carolina','state_code'=>'SC','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'South Dakota','state_code'=>'SD','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Tennessee','state_code'=>'TN','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Texas','state_code'=>'TX','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Utah','state_code'=>'UT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Vermont','state_code'=>'VT','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Virginia','state_code'=>'VA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Washington','state_code'=>'WA','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'West Virginia','state_code'=>'WV','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Wisconsin','state_code'=>'WI','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
          ['country_code'=>'US','state'=>'Wyoming','state_code'=>'WY','created_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ];
          State::insert($countries);
    }
}
